import Link from "next/link";
import { Metadata } from "next";
import { BreadcrumbSchema } from "@/components/StructuredData";

export const metadata: Metadata = {
  title: "Terms of Service — Reloca.ai",
  description: "Terms of service for using the Reloca.ai relocation intelligence platform.",
  openGraph: {
    title: "Terms of Service — Reloca.ai",
    description: "Terms of service for using the Reloca.ai relocation intelligence platform.",
    url: "https://reloca.ai/terms",
    type: "website",
    siteName: "Reloca.ai",
    images: [{ url: "https://reloca.ai/images/og-image.png", width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Terms of Service — Reloca.ai",
    description: "Terms of service for using the Reloca.ai relocation intelligence platform.",
    images: ["https://reloca.ai/images/og-image.png"],
  },
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#fafaf9]">
      <BreadcrumbSchema items={[{ name: "Terms of Service", url: "https://reloca.ai/terms" }]} />
      <header className="bg-white border-b border-gray-100 px-4 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center">
            <img 
              src="/images/reloca-logo.png" 
              alt="Reloca.ai" 
              className="h-13 w-auto"
            />
          </Link>
          <Link href="/" className="text-sm text-gray-400 hover:text-gray-600 transition">
            ← Back
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-[#1a365d] mb-8">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: February 16, 2026</p>

        <div className="prose prose-gray max-w-none space-y-6 text-gray-600 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">1. Agreement to Terms</h2>
            <p>By accessing or using Reloca.ai ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service.</p>
            <p>Reloca.ai is an AI-powered relocation intelligence platform ("we," "us," "our").</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">2. Description of Service</h2>
            <p>Reloca.ai is an AI-powered relocation planning platform that generates personalized relocation reports based on user-provided questionnaire responses. The Service includes:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li><strong>Free summary reports:</strong> A brief overview of your top country matches.</li>
              <li><strong>Paid full reports ($49):</strong> A comprehensive, multi-section relocation plan including visa options, cost of living, property market analysis, tax considerations, healthcare, education, and more.</li>
              <li><strong>Reloca Pro subscription ($29/month):</strong> Monthly access to generate one new report per month and receive Relocation Pulse intelligence updates.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">3. Important Disclaimers</h2>
            
            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">3.1 Not Legal, Financial, or Immigration Advice</h3>
            <p><strong>Reloca.ai reports are for informational and planning purposes only.</strong> They do not constitute legal, financial, tax, or immigration advice. Our reports are AI-generated based on publicly available data, proprietary research, and real-world experience — but they are not a substitute for professional advice.</p>
            <p><strong>You should always:</strong></p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>Consult a qualified immigration attorney before applying for any visa or residency.</li>
              <li>Consult a licensed tax advisor regarding your specific tax obligations.</li>
              <li>Consult a licensed real estate professional before purchasing property.</li>
              <li>Verify all information independently before making relocation decisions.</li>
            </ul>

            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">3.2 AI-Generated Content</h3>
            <p>Reports are generated by artificial intelligence (Anthropic's Claude API) based on your questionnaire responses and our knowledge base. While we strive for accuracy:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>AI can make errors or produce incomplete information.</li>
              <li>Data may not reflect the very latest changes in laws, regulations, or market conditions.</li>
              <li>Reports are based on general situations and may not account for your unique circumstances.</li>
            </ul>

            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">3.3 No Guarantees</h3>
            <p>We do not guarantee:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>The accuracy, completeness, or timeliness of any information in reports.</li>
              <li>Any specific outcome from following recommendations in a report.</li>
              <li>That visa applications, property purchases, or relocations will succeed.</li>
              <li>Uninterrupted or error-free operation of the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">4. User Accounts</h2>
            
            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">4.1 Account Creation</h3>
            <p>Reloca Pro subscribers must create an account. You are responsible for:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>Providing accurate information.</li>
              <li>Maintaining the security of your account credentials.</li>
              <li>All activity under your account.</li>
            </ul>

            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">4.2 Account Termination</h3>
            <p>We may suspend or terminate your account if you:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>Violate these Terms.</li>
              <li>Use the Service for fraudulent or illegal purposes.</li>
              <li>Attempt to reverse-engineer, scrape, or misuse our AI or data systems.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">5. Purchases and Payments</h2>
            
            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">5.1 Pricing</h3>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li><strong>Full report:</strong> $49 one-time payment.</li>
              <li><strong>Reloca Pro:</strong> $29/month recurring subscription.</li>
              <li>All prices are in US Dollars (USD).</li>
              <li>Prices may change with notice. Existing subscribers will be notified before any price increase takes effect.</li>
            </ul>

            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">5.2 Payment Processing</h3>
            <p>All payments are processed securely by Stripe. By making a purchase, you also agree to Stripe's terms of service.</p>

            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">5.3 Refund Policy</h3>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li><strong>Full reports ($49):</strong> All sales are final. Your report is generated and delivered immediately upon purchase. If you believe your report contains significant factual errors, contact <a href="mailto:support@reloca.ai" className="text-[#38b2ac] hover:underline">support@reloca.ai</a> within 7 days and we will either correct the report or issue a refund at our discretion.</li>
              <li><strong>Reloca Pro ($29/month):</strong> Cancel anytime. No refund for the current billing period. Cancellation takes effect at the end of the current billing period.</li>
              <li><strong>Free reports:</strong> No payment, no refund applicable.</li>
            </ul>

            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">5.4 EU Digital Content Waiver</h3>
            <p>By purchasing a report, you consent to immediate generation and delivery of digital content and acknowledge that you waive your right of withdrawal under the EU Distance Selling Directive once report generation begins.</p>

            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">5.5 Subscription Cancellation</h3>
            <p>Reloca Pro subscribers can cancel at any time through their account dashboard or by contacting <a href="mailto:support@reloca.ai" className="text-[#38b2ac] hover:underline">support@reloca.ai</a>. Upon cancellation:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>You retain access until the end of your current billing period.</li>
              <li>Previously generated reports remain accessible for 90 days after cancellation.</li>
              <li>After 90 days, report access is removed (you retain any downloaded PDFs).</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">6. Intellectual Property</h2>
            
            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">6.1 Our Content</h3>
            <p>All content on Reloca.ai — including text, graphics, logos, data compilations, AI models, report templates, and software — is owned by us or our licensors and is protected by intellectual property laws.</p>

            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">6.2 Your Reports</h3>
            <p>Reports generated for you are for your <strong>personal, non-commercial use</strong>. You may:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>Download, save, and print your reports.</li>
              <li>Share excerpts with your family, advisors, or professionals assisting your relocation.</li>
            </ul>
            <p>You may NOT:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>Resell, redistribute, or commercially exploit reports.</li>
              <li>Publish full reports publicly (blogs, social media, forums).</li>
              <li>Use reports to build competing products or services.</li>
            </ul>

            <h3 className="text-base font-semibold text-[#1a365d] mt-6 mb-2">6.3 Your Content</h3>
            <p>By submitting questionnaire responses, you grant us a non-exclusive, worldwide license to use that data (in anonymized, aggregated form) to improve our service and reports. Your individual responses are not shared publicly.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">7. Acceptable Use</h2>
            <p>You agree NOT to:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>Use the Service for any illegal purpose.</li>
              <li>Submit false or misleading information in the questionnaire.</li>
              <li>Attempt to access other users' accounts or data.</li>
              <li>Scrape, crawl, or automated-extract data from the Service.</li>
              <li>Reverse-engineer our AI models, algorithms, or knowledge base.</li>
              <li>Overload or interfere with the Service's infrastructure.</li>
              <li>Use the Service to generate reports for resale.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">8. Limitation of Liability</h2>
            <p><strong>To the maximum extent permitted by law:</strong></p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>Reloca.ai and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.</li>
              <li>Our total liability for any claim related to the Service shall not exceed the amount you paid us in the 12 months preceding the claim.</li>
              <li>We are not liable for any decisions you make based on report content, including relocation, financial, property, or immigration decisions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">9. Indemnification</h2>
            <p>You agree to indemnify and hold harmless Reloca.ai, Reloca.ai, and their operators, employees, and partners from any claims, damages, or expenses arising from:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>Your use of the Service.</li>
              <li>Your violation of these Terms.</li>
              <li>Your relocation decisions based on report content.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">10. Third-Party Services</h2>
            <p>The Service integrates with third-party providers:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li><strong>Stripe</strong> (payments)</li>
              <li><strong>Anthropic</strong> (AI report generation)</li>
              <li><strong>Email providers</strong> (report delivery)</li>
            </ul>
            <p>We are not responsible for the availability, accuracy, or policies of third-party services. Their respective terms and privacy policies apply.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">11. Modifications to Service and Terms</h2>
            <p>We reserve the right to:</p>
            <ul className="list-disc ml-6 space-y-1 mt-2">
              <li>Modify, suspend, or discontinue any part of the Service at any time.</li>
              <li>Update these Terms. Material changes will be communicated via email or website notice.</li>
              <li>Continued use after changes constitutes acceptance of updated Terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">12. Governing Law and Disputes</h2>
            <p>These Terms are governed by the laws of the Federative Republic of Brazil. Any disputes shall be resolved in the courts of Fortaleza, Ceará, Brazil.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">13. Severability</h2>
            <p>If any provision of these Terms is found to be unenforceable, the remainder shall remain in full force and effect.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#1a365d] mt-8 mb-3">14. Contact</h2>
            <p>Questions about these terms? Contact <a href="mailto:support@reloca.ai" className="text-[#38b2ac] hover:underline">support@reloca.ai</a>.</p>
          </section>
        </div>
      </main>
    </div>
  );
}