import { Question } from '@/types/questionnaire';

const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia',
  'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
  'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
  'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
  'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile',
  'China', 'Colombia', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
  'Czech Republic', 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
  'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Georgia', 'Germany', 'Ghana',
  'Greece', 'Guatemala', 'Guinea', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India',
  'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
  'Jordan', 'Kazakhstan', 'Kenya', 'Kuwait', 'Latvia', 'Lebanon', 'Libya',
  'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malaysia', 'Mali', 'Malta',
  'Mexico', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
  'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger',
  'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Paraguay',
  'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
  'Saudi Arabia', 'Senegal', 'Serbia', 'Singapore', 'Slovakia', 'Slovenia',
  'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'Sudan', 'Sweden', 'Switzerland',
  'Syria', 'Taiwan', 'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
  'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
  'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia',
  'Zimbabwe',
];

const LATAM_COUNTRIES = [
  'Argentina', 'Belize', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Costa Rica',
  'Cuba', 'Dominican Republic', 'Ecuador', 'El Salvador', 'Guatemala', 'Haiti',
  'Honduras', 'Mexico', 'Nicaragua', 'Panama', 'Paraguay', 'Peru', 'Uruguay',
  'Venezuela',
];

// Countries with full or partial coverage (Tier 1 + Tier 2)
export const COVERED_COUNTRIES = [
  // LATAM
  'Argentina', 'Brazil', 'Paraguay', 'Uruguay', 'Panama', 'El Salvador',
  // Europe
  'Portugal', 'Andorra', 'Italy', 'Spain', 'Greece',
  // Future phases will add: UAE, Georgia, Turkey, Malaysia, Thailand, Singapore, etc.
];

export { COUNTRIES, LATAM_COUNTRIES };

export const questions: Question[] = [
  // SECTION 1: WHO ARE YOU
  {
    id: 1,
    section: 1,
    sectionTitle: 'Who Are You',
    question: "What's your nationality?",
    type: 'dropdown',
    mandatory: true,
    options: COUNTRIES.map(c => ({ value: c, label: c })),
  },
  {
    id: 2,
    section: 1,
    sectionTitle: 'Who Are You',
    question: 'Current country of residence?',
    type: 'dropdown',
    mandatory: true,
    options: COUNTRIES.map(c => ({ value: c, label: c })),
  },
  {
    id: 3,
    section: 1,
    sectionTitle: 'Who Are You',
    question: 'Age range?',
    type: 'select',
    mandatory: false,
    options: [
      { value: '20s', label: '20s' },
      { value: '30s', label: '30s' },
      { value: '40s', label: '40s' },
      { value: '50s', label: '50s' },
      { value: '60+', label: '60+' },
    ],
  },
  {
    id: 4,
    section: 1,
    sectionTitle: 'Who Are You',
    question: 'Family composition?',
    type: 'select',
    mandatory: true,
    options: [
      { value: 'single', label: 'Single' },
      { value: 'couple', label: 'Couple' },
      { value: 'family', label: 'Family with kids' },
    ],
  },
  {
    id: 5,
    section: 1,
    sectionTitle: 'Who Are You',
    question: 'If family: ages of children?',
    type: 'text',
    mandatory: false,
    placeholder: 'e.g., 3, 7, 12',
    conditionalOn: { questionId: 4, value: 'family' },
  },
  {
    id: 6,
    section: 1,
    sectionTitle: 'Who Are You',
    question: 'Languages you speak?',
    type: 'multi-select',
    mandatory: false,
    options: [
      { value: 'en', label: 'English' },
      { value: 'fr', label: 'French' },
      { value: 'pt', label: 'Portuguese' },
      { value: 'es', label: 'Spanish' },
      { value: 'de', label: 'German' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 7,
    section: 1,
    sectionTitle: 'Who Are You',
    question: 'Languages willing to learn?',
    type: 'multi-select',
    mandatory: false,
    options: [
      { value: 'en', label: 'English' },
      { value: 'fr', label: 'French' },
      { value: 'pt', label: 'Portuguese' },
      { value: 'es', label: 'Spanish' },
      { value: 'de', label: 'German' },
      { value: 'other', label: 'Other' },
    ],
  },

  // SECTION 2: FINANCIAL PICTURE
  {
    id: 8,
    section: 2,
    sectionTitle: 'Financial Picture',
    question: 'Work situation?',
    type: 'select',
    mandatory: true,
    options: [
      { value: 'employee', label: 'Employee' },
      { value: 'remote', label: 'Remote Worker' },
      { value: 'entrepreneur', label: 'Entrepreneur' },
      { value: 'retired', label: 'Retired' },
      { value: 'student', label: 'Student' },
    ],
  },
  {
    id: 9,
    section: 2,
    sectionTitle: 'Financial Picture',
    question: 'Industry/profession?',
    type: 'dropdown',
    mandatory: false,
    options: [
      { value: 'tech', label: 'Technology / IT' },
      { value: 'finance', label: 'Finance / Banking' },
      { value: 'healthcare', label: 'Healthcare' },
      { value: 'education', label: 'Education' },
      { value: 'marketing', label: 'Marketing / Media' },
      { value: 'legal', label: 'Legal' },
      { value: 'consulting', label: 'Consulting' },
      { value: 'real-estate', label: 'Real Estate' },
      { value: 'hospitality', label: 'Hospitality / Tourism' },
      { value: 'creative', label: 'Creative / Design' },
      { value: 'engineering', label: 'Engineering' },
      { value: 'retail', label: 'Retail / E-commerce' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 10,
    section: 2,
    sectionTitle: 'Financial Picture',
    question: 'Monthly income range?',
    type: 'select',
    mandatory: true,
    options: [
      { value: '<2k', label: 'Less than $2,000' },
      { value: '2-5k', label: '$2,000 – $5,000' },
      { value: '5-10k', label: '$5,000 – $10,000' },
      { value: '10-20k', label: '$10,000 – $20,000' },
      { value: '20k+', label: '$20,000+' },
    ],
  },
  {
    id: 11,
    section: 2,
    sectionTitle: 'Financial Picture',
    question: 'Property/investment budget?',
    type: 'select',
    mandatory: false,
    options: [
      { value: '<100k', label: 'Less than $100K' },
      { value: '100-300k', label: '$100K – $300K' },
      { value: '300-500k', label: '$300K – $500K' },
      { value: '500k-1m', label: '$500K – $1M' },
      { value: '1m+', label: '$1M+' },
    ],
  },
  {
    id: 12,
    section: 2,
    sectionTitle: 'Financial Picture',
    question: 'Existing assets abroad?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
    ],
  },
  {
    id: 13,
    section: 2,
    sectionTitle: 'Financial Picture',
    question: 'Income source after relocating?',
    type: 'multi-select',
    mandatory: false,
    options: [
      { value: 'remote-job', label: 'Remote job' },
      { value: 'business', label: 'Business' },
      { value: 'investments', label: 'Investments' },
      { value: 'pension', label: 'Pension' },
      { value: 'other', label: 'Other' },
    ],
  },

  // SECTION 3: DESTINATION
  {
    id: 14,
    section: 3,
    sectionTitle: 'Destination',
    question: 'Already chosen a country?',
    type: 'select',
    mandatory: true,
    options: [
      { value: 'exploring', label: 'Still exploring' },
      { value: 'no-idea', label: 'No idea yet' },
      ...COUNTRIES.map(c => ({ value: c.toLowerCase(), label: `Yes — ${c}` })),
    ],
  },
  {
    id: 15,
    section: 3,
    sectionTitle: 'Destination',
    question: 'Visited any countries you are considering?',
    type: 'multi-select',
    mandatory: false,
    options: LATAM_COUNTRIES.map(c => ({ value: c.toLowerCase(), label: c })),
  },
  {
    id: 16,
    section: 3,
    sectionTitle: 'Destination',
    question: 'Climate preference?',
    type: 'select',
    mandatory: true,
    options: [
      { value: 'tropical', label: 'Tropical' },
      { value: 'subtropical', label: 'Subtropical' },
      { value: 'four-seasons', label: 'Four seasons' },
      { value: 'mountain-cool', label: 'Mountain cool' },
      { value: 'flexible', label: 'Flexible' },
    ],
  },
  {
    id: 17,
    section: 3,
    sectionTitle: 'Destination',
    question: 'Environment preference?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'beach', label: 'Beach' },
      { value: 'mountain', label: 'Mountain' },
      { value: 'city', label: 'City' },
      { value: 'countryside', label: 'Countryside' },
      { value: 'mix', label: 'Mix' },
    ],
  },
  {
    id: 18,
    section: 3,
    sectionTitle: 'Destination',
    question: 'City size preference?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'major', label: 'Major city' },
      { value: 'mid-size', label: 'Mid-size city' },
      { value: 'small-town', label: 'Small town' },
      { value: 'rural', label: 'Rural' },
    ],
  },
  {
    id: 19,
    section: 3,
    sectionTitle: 'Destination',
    question: 'Rank your top 3 priorities:',
    type: 'multi-select',
    mandatory: false,
    options: [
      { value: 'safety', label: 'Safety' },
      { value: 'cost', label: 'Cost of living' },
      { value: 'climate', label: 'Climate' },
      { value: 'nature', label: 'Nature' },
      { value: 'community', label: 'Expat community' },
      { value: 'tax', label: 'Tax benefits' },
      { value: 'healthcare', label: 'Healthcare' },
      { value: 'schools', label: 'Schools' },
      { value: 'internet', label: 'Internet quality' },
      { value: 'culture', label: 'Culture' },
    ],
  },

  // SECTION 4: CONCERNS
  {
    id: 20,
    section: 4,
    sectionTitle: 'Concerns',
    question: 'Biggest concerns about relocating?',
    type: 'multi-select',
    mandatory: false,
    options: [
      { value: 'language', label: 'Language barrier' },
      { value: 'bureaucracy', label: 'Bureaucracy' },
      { value: 'safety', label: 'Safety' },
      { value: 'healthcare', label: 'Healthcare quality' },
      { value: 'schools', label: 'Schools' },
      { value: 'loneliness', label: 'Loneliness' },
      { value: 'politics', label: 'Political instability' },
      { value: 'currency', label: 'Currency volatility' },
      { value: 'work', label: 'Finding work' },
      { value: 'legal', label: 'Legal complexity' },
      { value: 'culture', label: 'Culture shock' },
      { value: 'distance', label: 'Distance from family' },
    ],
  },
  {
    id: 21,
    section: 4,
    sectionTitle: 'Concerns',
    question: 'How sensitive are you to bureaucracy? (1 = very patient, 5 = cannot stand it)',
    type: 'scale',
    mandatory: false,
  },
  {
    id: 22,
    section: 4,
    sectionTitle: 'Concerns',
    question: 'How important is tax optimization?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'not-at-all', label: 'Not at all' },
      { value: 'nice-to-have', label: 'Nice to have' },
      { value: 'very', label: 'Very important' },
      { value: 'main-reason', label: "It's a main reason for moving" },
    ],
  },
  {
    id: 23,
    section: 4,
    sectionTitle: 'Concerns',
    question: 'Need international schools?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'yes-english', label: 'Yes — English' },
      { value: 'yes-french', label: 'Yes — French' },
      { value: 'yes-other', label: 'Yes — Other language' },
      { value: 'no', label: 'No' },
      { value: 'na', label: 'Not applicable' },
    ],
  },

  // SECTION 5: TIMELINE
  {
    id: 24,
    section: 5,
    sectionTitle: 'Timeline',
    question: 'When do you want to move?',
    type: 'select',
    mandatory: true,
    options: [
      { value: 'already-there', label: 'Already there' },
      { value: '3-months', label: 'Within 3 months' },
      { value: '6-months', label: 'Within 6 months' },
      { value: '1-year', label: 'Within 1 year' },
      { value: '2-years', label: '2+ years' },
      { value: 'exploring', label: 'Just exploring' },
    ],
  },
  {
    id: 25,
    section: 5,
    sectionTitle: 'Timeline',
    question: 'Relocation style?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'all-in', label: 'All-in move' },
      { value: 'test-visits', label: 'Test visits first' },
      { value: 'slow-transition', label: 'Slow transition' },
      { value: 'split-time', label: 'Split time between countries' },
    ],
  },
  {
    id: 26,
    section: 5,
    sectionTitle: 'Timeline',
    question: 'Property: buy or rent?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'buy', label: 'Buy' },
      { value: 'rent', label: 'Rent first' },
      { value: 'both', label: 'Open to both' },
      { value: 'not-sure', label: 'Not sure yet' },
    ],
  },
  {
    id: 27,
    section: 5,
    sectionTitle: 'Timeline',
    question: 'If buying, what type of property?',
    type: 'multi-select',
    mandatory: false,
    options: [
      { value: 'apartment', label: 'Apartment' },
      { value: 'house', label: 'House' },
      { value: 'land', label: 'Land' },
      { value: 'farm', label: 'Farm' },
      { value: 'commercial', label: 'Commercial' },
      { value: 'investment', label: 'Investment property' },
    ],
  },
  {
    id: 28,
    section: 5,
    sectionTitle: 'Timeline',
    question: 'Interest in an expat community/development?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'maybe', label: 'Maybe' },
      { value: 'no', label: 'No' },
    ],
  },

  // SECTION 6: LIFESTYLE & VALUES
  {
    id: 29,
    section: 6,
    sectionTitle: 'Lifestyle & Values',
    question: "What's driving your move?",
    type: 'multi-select',
    mandatory: false,
    options: [
      { value: 'freedom', label: 'Freedom' },
      { value: 'lower-cost', label: 'Lower cost of living' },
      { value: 'weather', label: 'Weather' },
      { value: 'nature', label: 'Nature' },
      { value: 'adventure', label: 'Adventure' },
      { value: 'kids-future', label: "Kids' future" },
      { value: 'tax', label: 'Tax benefits' },
      { value: 'politics', label: 'Political reasons' },
      { value: 'wellness', label: 'Wellness' },
      { value: 'business', label: 'Business opportunity' },
      { value: 'retirement', label: 'Retirement' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 30,
    section: 6,
    sectionTitle: 'Lifestyle & Values',
    question: 'Health/wellness priorities?',
    type: 'multi-select',
    mandatory: false,
    options: [
      { value: 'organic-food', label: 'Organic food' },
      { value: 'outdoor-sports', label: 'Outdoor sports' },
      { value: 'clean-air', label: 'Clean air' },
      { value: 'alternative-medicine', label: 'Alternative medicine' },
      { value: 'none', label: 'None in particular' },
    ],
  },
  {
    id: 31,
    section: 6,
    sectionTitle: 'Lifestyle & Values',
    question: 'Expat community or local immersion?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'expat', label: 'Expat community' },
      { value: 'immersion', label: 'Full local immersion' },
      { value: 'mix', label: 'Mix of both' },
    ],
  },
  {
    id: 32,
    section: 6,
    sectionTitle: 'Lifestyle & Values',
    question: 'What internet speed do you need for your daily life?',
    type: 'select',
    mandatory: false,
    options: [
      { value: 'basic', label: 'Basic — email, browsing, social media' },
      { value: 'video-calls', label: 'Moderate — video calls, streaming' },
      { value: 'heavy-remote', label: 'Fast — remote work with large files, multiple video calls' },
      { value: 'content-creation', label: 'Ultra-fast — video editing, content creation, gaming' },
      { value: 'dont-care', label: "Not important to me" },
    ],
  },
  {
    id: 33,
    section: 6,
    sectionTitle: 'Lifestyle & Values',
    question: 'Values alignment (rate each 1-5):',
    type: 'sliders',
    mandatory: false,
    sliders: [
      { label: 'Government involvement', min: 1, max: 5 },
      { label: 'Personal freedom', min: 1, max: 5 },
      { label: 'Homeschool freedom', min: 1, max: 5 },
      { label: 'Traditional values', min: 1, max: 5 },
      { label: 'Environmental regulations', min: 1, max: 5 },
    ],
  },

  // SECTION 7: FINAL
  {
    id: 34,
    section: 7,
    sectionTitle: 'Final',
    question: 'Describe your dream life abroad (one sentence)',
    type: 'text',
    mandatory: false,
    placeholder: 'e.g., "Living by the beach, working remotely, kids in a bilingual school"',
    maxLength: 200,
  },
  {
    id: 35,
    section: 7,
    sectionTitle: 'Final',
    question: 'ONE question you most want answered?',
    type: 'text',
    mandatory: false,
    placeholder: 'e.g., "Can I keep my US health insurance while living in Brazil?"',
    maxLength: 200,
  },
  {
    id: 36,
    section: 7,
    sectionTitle: 'Final',
    question: 'How did you hear about Reloca.ai?',
    type: 'select',
    mandatory: true,
    options: [
      { value: 'google', label: 'Google' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'twitter', label: 'X / Twitter' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'friend', label: 'Friend / Word of mouth' },
      { value: 'reloca-ai', label: 'Reloca.ai' },
      { value: 'reddit', label: 'Reddit' },
      { value: 'other', label: 'Other' },
    ],
  },
];

export const MANDATORY_QUESTIONS = [1, 2, 4, 8, 10, 14, 16, 24, 36];
export const TOTAL_QUESTIONS = 36;
export const SECTIONS = [
  { id: 1, title: 'Who Are You', questions: [1, 2, 3, 4, 5, 6, 7] },
  { id: 2, title: 'Financial Picture', questions: [8, 9, 10, 11, 12, 13] },
  { id: 3, title: 'Destination', questions: [14, 15, 16, 17, 18, 19] },
  { id: 4, title: 'Concerns', questions: [20, 21, 22, 23] },
  { id: 5, title: 'Timeline', questions: [24, 25, 26, 27, 28] },
  { id: 6, title: 'Lifestyle & Values', questions: [29, 30, 31, 32, 33] },
  { id: 7, title: 'Final', questions: [34, 35, 36] },
];
